language: ruby
rvm:
- 2.4.1

before_script:
 - chmod +x ./ci/build
 - chmod +x ./ci/deploy

script: ./ci/build

after_success: ./ci/deploy

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false